using Xunit;
using DamonAllison.CSharpTests.Objects;
using System.Collections.Generic;

namespace DamonAllison.CSharpTests
{
    public class ObjectTests 
    {

        [Fact]
        public void InitializerTest()  
        {
            // C# 3.0 added object initializers. Object initializers
            // allow you to set field / property values on the object.
            // 
            // This is strictly syntactic sugar. The IL generated by 
            // object initializers is exactly the same as if you would manually
            // set properties following the creation of the object.
            Person p = new Person() 
            {
                FirstName = "Damon", 
                LastName = "Allison"
            };
            
        }
        public void CollectionInitializerTest() 
        {
            // C# 3.0 added collection initializers. 
            // Collection initializers allow you to add elements to the collection 
            // at instiantiation.
            IList<Person> family = new List<Person>() 
            {
                new Person() 
                {
                    FirstName = "Damon", 
                    LastName = "Allison"
                },
                new Person() 
                {
                    FirstName = "Kari", 
                    LastName = "Allison"
                } 
            };
            Assert.Equal(2, family.Count);
        }
    }
}